import fs from "fs";

const memes = [
  "pepe",
  "doge",
  "wojak",
  "spongebob",
  "mocking spongebob",
  "woman yelling at a cat",
  "arthur fist",
  "expanding brain",
  "this is fine",
  "two buttons",
  "bongo cat",
  "change my mind",
  "surprised pikachu",
  "blinking white guy",
  "distracted boyfriend",
  "roll safe",
  "unsettled tom",
  "hide the pain harold",
  "drake hotline bling",
  "is this a pigeon?",
  "harambe",
  "big chungus",
  "stonks",
  "peekaboo crab",
  "homer simpson backs into bushes",
  "dank memes",
  "rickroll",
  "screaming cowboy",
  "sad keanu",
  "salt bae",
  "you don't say?",
  "one does not simply",
  "crying jordan",
  "y u no",
  "dank",
  "bruh",
  "yeet",
  "oof",
  "shrek",
  "baby yoda",
  "dat boi",
  "ugandan knuckles",
  "grumpy cat",
  "nyan cat",
  "futurama fry",
  "forever alone",
  "success kid",
  "bad luck brian",
  "troll face",
  "pepe silvia",
  "karen",
  "karen haircut",
];

const easy = [
  "sun",
  "cat",
  "dog",
  "fish",
  "moon",
  "star",
  "tree",
  "bird",
  "cake",
  "flower",
  "smile",
  "heart",
  "cloud",
  "pizza",
  "guitar",
  "beach",
  "rocket",
  "castle",
  "car",
  "boat",
  "rainbow",
  "apple",
  "banana",
  "book",
  "hat",
  "ball",
  "circle",
  "square",
  "turtle",
  "dolphin",
  "robot",
  "wizard",
  "dragon",
  "unicorn",
  "pencil",
  "ocean",
  "planet",
  "lollipop",
  "crown",
  "tiger",
  "elephant",
  "ladybug",
  "butterfly",
  "panda",
  "parrot",
  "sailboat",
  "strawberry",
  "popsicle",
  "dinosaur",
  "mermaid",
  "kangaroo",
  "jellyfish",
  "flamingo",
  "whale",
  "octopus",
  "volcano",
  "raindrops",
  "mushroom",
  "snowflake",
  "spaceship",
  "cactus",
  "helicopter",
  "donut",
  "fireworks",
  "koala",
  "mitten",
  "ninja",
  "pineapple",
  "seashell",
  "taco",
  "watermelon",
  "xylophone",
  "zebra",
  "cupcake",
  "giraffe",
  "hamburger",
  "yogurt",
  "alien",
  "kite",
  "muffin",
  "quilt",
  "volleyball",
  "globe",
  "zucchini",
  "squid",
  "comet",
  "tornado",
  "tiara",
  "castle",
  "robot",
  "astronaut",
  "skateboard",
  "carousel",
  "gumball",
  "caterpillar",
  "spaceship",
  "vampire",
  "skyscraper",
  "chameleon",
  "trombone",
];

const phrases = [
  "time flies",
  "piece of cake",
  "break a leg",
  "bite the bullet",
  "the early bird catches the worm",
  "a penny for your thoughts",
  "actions speak louder than words",
  "blessing in disguise",
  "curiosity killed the cat",
  "don't cry over spilled milk",
  "every cloud has a silver lining",
  "fool's paradise",
  "haste makes waste",
  "in the nick of time",
  "jump on the bandwagon",
  "kill two birds with one stone",
  "look before you leap",
  "make hay while the sun shines",
  "no pain no gain",
  "on cloud nine",
  "practice makes perfect",
  "quick as a flash",
  "rome wasn't built in a day",
  "strike while the iron is hot",
  "the best of both worlds",
  "under the weather",
  "variety is the spice of life",
  "when pigs fly",
  "you can't judge a book by its cover",
  "zero tolerance",
];

const games = [
  "minecraft",
  "overwatch",
  "zelda",
  "pokemon",
  "tetris",
  "sims",
  "mario",
  "fallout",
  "portal",
  "doom",
  "journey",
  "splatoon",
  "skyrim",
  "undertale",
  "assassins creed",
  "dark souls",
  "pokken",
  "rocket league",
  "shadow of the colossus",
  "monster hunter",
  "limbo",
  "celeste",
  "rayman",
  "cave story",
  "flower",
  "dont starve",
  "binding of isaac",
  "megalomania",
  "spelunky",
  "paper mario",
  "stardew valley",
  "diablo",
  "resident evil",
  "bloodborne",
  "firewatch",
  "nintendogs",
  "fez",
  "street fighter",
  "limbo",
  "undertale",
  "bastion",
  "limbo",
  "bioshock",
  "portal",
  "journey",
  "limbo",
  "firewatch",
  "nier",
  "hollow knight",
  "horizon",
  "undertale",
  "zelda",
  "witcher",
  "mario",
  "portal",
  "god of war",
  "final fantasy",
  "skyrim",
  "doom",
  "celeste",
  "fallout",
  "cave story",
  "bloodborne",
  "dark souls",
  "journey",
  "undertale",
  "limbo",
  "shadow of the colossus",
  "flower",
  "stardew valley",
  "binding of isaac",
  "diablo",
  "spelunky",
  "paper mario",
  "rocket league",
  "fez",
  "resident evil",
  "horizon",
  "nier automata",
  "mario",
  "final fantasy",
  "zelda",
  "celeste",
  "witcher",
  "god of war",
  "bloodborne",
  "doom",
  "firewatch",
  "nier",
  "megalomania",
];

const anime = [
  "naruto",
  "pokemon",
  "one piece",
  "dragon ball",
  "sailor moon",
  "my neighbor totoro",
  "hello kitty",
  "doraemon",
  "attack on titan",
  "bleach",
  "fairy tail",
  "death note",
  "tokyo ghoul",
  "black clover",
  "dragon ball z",
  "my hero academia",
  "one punch man",
  "hunter x hunter",
  "spirited away",
  "naruto shippuden",
  "fullmetal alchemist",
  "demon slayer",
  "soul eater",
  "inuyasha",
  "yu-gi-oh!",
  "beyblade",
  "case closed",
  "fate/stay night",
  "toradora!",
  "sword art online",
  "k-on!",
  "your lie in april",
  "noragami",
  "neon genesis evangelion",
  "bleach",
  "nana",
  "clannad",
  "ouran high school host club",
  "fairy tail",
  "pokemon",
  "cardcaptor sakura",
  "sakura wars",
  "bleach",
  "digimon",
  "death note",
  "black clover",
  "attack on titan",
  "one piece",
  "dragon ball",
  "naruto",
  "one punch man",
  "my hero academia",
  "sailor moon",
  "hunter x hunter",
  "spirited away",
  "demon slayer",
  "tokyo ghoul",
  "fate/stay night",
  "dragon ball z",
  "fullmetal alchemist",
  "yu yu hakusho",
  "sword art online",
  "pokemon",
  "death note",
  "fairy tail",
  "bleach",
  "one piece",
  "naruto",
  "dragon ball",
  "attack on titan",
  "sailor moon",
  "my hero academia",
  "one punch man",
  "hunter x hunter",
  "spirited away",
  "tokyo ghoul",
  "fate/stay night",
  "black clover",
  "demon slayer",
  "sword art online",
  "pokemon",
  "bleach",
  "fairy tail",
  "death note",
  "dragon ball z",
  "fullmetal alchemist",
  "naruto shippuden",
  "my hero academia",
  "one punch man",
  "attack on titan",
  "hunter x hunter",
  "spirited away",
  "tokyo ghoul",
  "demon slayer",
  "fate/stay night",
  "sword art online",
  "pokemon",
  "bleach",
  "fairy tail",
  "death note",
  "black clover",
  "dragon ball z",
  "one piece",
  "naruto",
  "attack on titan",
  "sailor moon",
  "my hero academia",
  "one punch man",
  "hunter x hunter",
];

const movies = [
  "frozen",
  "finding nemo",
  "toy story",
  "the lion king",
  "moana",
  "shrek",
  "frozen ii",
  "cars",
  "minions",
  "zootopia",
  "the little mermaid",
  "despicable me",
  "coco",
  "madagascar",
  "tangled",
  "ratatouille",
  "inside out",
  "finding dory",
  "up",
  "brave",
  "wreck-it ralph",
  "the incredibles",
  "monsters, inc.",
  "peter pan",
  "tarzan",
  "mulan",
  "aladdin",
  "cinderella",
  "beauty and the beast",
  "hercules",
  "sleeping beauty",
  "snow white and the seven dwarfs",
  "pinocchio",
  "the princess and the frog",
  "the jungle book",
  "dumbo",
  "bambi",
  "the aristocats",
  "101 dalmatians",
  "robin hood",
  "the sword in the stone",
  "the hunchback of notre dame",
  "the little mermaid",
  "pocahontas",
  "tarzan",
  "mulan",
  "brother bear",
  "finding nemo",
  "the incredibles",
  "cars",
  "ratatouille",
  "wall-e",
  "up",
  "toy story 3",
  "tangled",
  "brave",
  "frozen",
  "inside out",
  "zootopia",
  "moana",
  "coco",
  "frozen ii",
  "the lion king",
  "the little mermaid",
  "aladdin",
  "beauty and the beast",
  "cinderella",
  "hercules",
  "peter pan",
  "tarzan",
  "mulan",
  "sleeping beauty",
  "snow white and the seven dwarfs",
  "pinocchio",
  "the princess and the frog",
  "the jungle book",
  "dumbo",
  "bambi",
  "the aristocats",
  "101 dalmatians",
  "robin hood",
  "the sword in the stone",
  "the hunchback of notre dame",
  "pocahontas",
  "the emperor's new groove",
  "lilo & stitch",
  "the fox and the hound",
  "dinosaur",
  "the rescuers",
  "alice in wonderland",
  "the black cauldron",
  "the great mouse detective",
  "oliver & company",
  "the rescuers down under",
  "beauty and the beast",
  "aladdin",
  "the nightmare before christmas",
  "the santa clause",
  "home alone",
  "the grinch",
  "elf",
  "polar express",
  "a christmas carol",
  "shrek",
  "despicable me",
  "frozen",
  "finding nemo",
  "the lion king",
  "cars",
  "zootopia",
  "tangled",
  "moana",
  "coco",
  "up",
];

const shows = [
  "spongebob squarepants",
  "the simpsons",
  "rick and morty",
  "family guy",
  "south park",
  "peppa pig",
  "dora the explorer",
  "paw patrol",
  "teletubbies",
  "wallykazam",
  "blue's clues",
  "pokemon",
  "yo gabba gabba!",
  "sesame street",
  "thomas & friends",
  "mickey mouse clubhouse",
  "barney & friends",
  "peppa pig",
  "curious george",
  "doc mcstuffins",
  "dora the explorer",
  "paw patrol",
  "peppa pig",
  "bluey",
  "the wiggles",
  "octonauts",
  "blues clues",
  "mickey mouse clubhouse",
  "pj masks",
  "shaun the sheep",
  "ryan's world",
  "bob the builder",
  "fireman sam",
  "super why!",
  "clifford the big red dog",
  "ben & holly's little kingdom",
  "chuggington",
  "daniel tiger's neighborhood",
  "peppa pig",
  "bubble guppies",
  "team umizoomi",
  "wallykazam",
  "go, diego, go!",
  "blaze and the monster machines",
  "pj masks",
  "peppa pig",
  "mickey mouse clubhouse",
  "the backyardigans",
  "doc mcstuffins",
  "the wiggles",
  "octonauts",
  "little einsteins",
  "blue's clues",
  "team umizoomi",
  "bubble guppies",
  "peppa pig",
  "dora and friends",
  "the lion guard",
  "peter rabbit",
  "peppa pig",
  "pj masks",
  "mickey mouse mixed-up adventures",
  "vampirina",
  "bluey",
  "ducktales",
  "scooby-doo",
  "peppa pig",
  "the flintstones",
  "ben 10",
  "spongebob squarepants",
  "the simpsons",
  "rick and morty",
  "family guy",
  "south park",
  "the office",
  "friends",
  "stranger things",
  "game of thrones",
  "breaking bad",
  "the big bang theory",
  "the simpsons",
  "family guy",
  "rick and morty",
  "south park",
  "the office",
  "friends",
  "stranger things",
  "game of thrones",
  "breaking bad",
  "the big bang theory",
  "modern family",
  "the walking dead",
  "the simpsons",
  "family guy",
  "rick and morty",
  "south park",
  "the office",
  "friends",
  "stranger things",
  "game of thrones",
  "breaking bad",
  "the big bang theory",
  "modern family",
  "the walking dead",
];

const books = [
  "charlotte's web",
  "the very hungry caterpillar",
  "green eggs and ham",
  "where the wild things are",
  "the cat in the hat",
  "goodnight moon",
  "brown bear, brown bear, what do you see?",
  "corduroy",
  "the giving tree",
  "curious george",
  "harold and the purple crayon",
  "the gruffalo",
  "winnie-the-pooh",
  "if you give a mouse a cookie",
  "madeline",
  "peter rabbit",
  "the tale of despereaux",
  "the little prince",
  "where the sidewalk ends",
  "the wind in the willows",
  "the velveteen rabbit",
  "winnie-the-pooh",
  "the hobbit",
  "alice's adventures in wonderland",
  "the secret garden",
  "the adventures of tom sawyer",
  "the bfg",
  "the chronicles of narnia",
  "the jungle book",
  "harry potter and the sorcerer's stone",
  "the wizard of oz",
  "the lion, the witch and the wardrobe",
  "alice in wonderland",
  "charlie and the chocolate factory",
  "matilda",
  "the tale of peter rabbit",
  "the wind in the willows",
  "the little prince",
  "winnie-the-pooh",
  "the hobbit",
  "alice's adventures in wonderland",
  "the secret garden",
  "the adventures of tom sawyer",
  "the bfg",
  "the chronicles of narnia",
  "the jungle book",
  "the lord of the rings",
  "harry potter and the sorcerer's stone",
  "the wizard of oz",
  "the lion, the witch and the wardrobe",
  "alice in wonderland",
  "charlie and the chocolate factory",
  "matilda",
  "the tale of peter rabbit",
  "the wind in the willows",
  "the little prince",
  "winnie-the-pooh",
  "the hobbit",
  "alice's adventures in wonderland",
  "the secret garden",
  "the adventures of tom sawyer",
  "the bfg",
  "the chronicles of narnia",
  "the jungle book",
  "the lord of the rings",
  "harry potter and the sorcerer's stone",
  "the wizard of oz",
  "the lion, the witch and the wardrobe",
  "alice in wonderland",
  "charlie and the chocolate factory",
  "matilda",
  "the tale of peter rabbit",
  "the wind in the willows",
  "the little prince",
  "winnie-the-pooh",
  "the hobbit",
  "alice's adventures in wonderland",
  "the secret garden",
  "the adventures of tom sawyer",
  "the bfg",
  "the chronicles of narnia",
  "the jungle book",
  "the lord of the rings",
  "harry potter and the sorcerer's stone",
  "the wizard of oz",
  "the lion, the witch and the wardrobe",
  "alice in wonderland",
  "charlie and the chocolate factory",
  "matilda",
  "the tale of peter rabbit",
  "the wind in the willows",
  "the little prince",
  "winnie-the-pooh",
  "the hobbit",
  "alice's adventures in wonderland",
  "the secret garden",
  "the adventures of tom sawyer",
  "the bfg",
  "the chronicles of narnia",
  "the jungle book",
  "the lord of the rings",
  "harry potter and the sorcerer's stone",
  "the wizard of oz",
  "the lion, the witch and the wardrobe",
  "alice in wonderland",
  "charlie and the chocolate factory",
  "matilda",
  "the tale of peter rabbit",
];

const foods = [
  "apple",
  "banana",
  "orange",
  "strawberry",
  "grapes",
  "watermelon",
  "kiwi",
  "mango",
  "blueberry",
  "pineapple",
  "lemon",
  "peach",
  "pear",
  "plum",
  "cherry",
  "raspberry",
  "blackberry",
  "apricot",
  "pomegranate",
  "coconut",
  "avocado",
  "guava",
  "fig",
  "cantaloupe",
  "honeydew",
  "papaya",
  "passion fruit",
  "dragon fruit",
  "apricot",
  "carrot",
  "broccoli",
  "cucumber",
  "lettuce",
  "tomato",
  "potato",
  "onion",
  "garlic",
  "bell pepper",
  "zucchini",
  "eggplant",
  "corn",
  "peas",
  "green beans",
  "asparagus",
  "spinach",
  "cabbage",
  "cauliflower",
  "sweet potato",
  "pumpkin",
  "butternut squash",
  "beetroot",
  "radish",
  "leek",
  "celery",
  "mushroom",
  "garbanzo beans",
  "lentils",
  "kidney beans",
  "black beans",
  "chickpeas",
  "quinoa",
  "rice",
  "pasta",
  "bread",
  "baguette",
  "croissant",
  "pancake",
  "waffle",
  "toast",
  "burger",
  "pizza",
  "hot dog",
  "sandwich",
  "taco",
  "burrito",
  "sushi",
  "ramen",
  "pasta",
  "noodles",
  "fried chicken",
  "steak",
  "salmon",
  "shrimp",
  "lobster",
  "crab",
  "bacon",
  "sausage",
  "ham",
  "egg",
  "cheese",
  "yogurt",
  "milk",
  "butter",
  "ice cream",
  "chocolate",
  "cake",
  "cupcake",
  "cookie",
  "donut",
  "pie",
  "brownie",
  "macaron",
  "muffin",
];

const countries = [
  "afghanistan",
  "albania",
  "algeria",
  "andorra",
  "angola",
  "antigua and barbuda",
  "argentina",
  "armenia",
  "australia",
  "austria",
  "azerbaijan",
  "bahamas",
  "bahrain",
  "bangladesh",
  "barbados",
  "belarus",
  "belgium",
  "belize",
  "benin",
  "bhutan",
  "bolivia",
  "bosnia and herzegovina",
  "botswana",
  "brazil",
  "brunei",
  "bulgaria",
  "burkina faso",
  "burundi",
  "cabo verde",
  "cambodia",
  "cameroon",
  "canada",
  "central african republic",
  "chad",
  "chile",
  "china",
  "colombia",
  "comoros",
  "congo",
  "costa rica",
  "croatia",
  "cuba",
  "cyprus",
  "czechia",
  "denmark",
  "djibouti",
  "dominica",
  "dominican republic",
  "ecuador",
  "egypt",
  "el salvador",
  "equatorial guinea",
  "eritrea",
  "estonia",
  "eswatini",
  "ethiopia",
  "fiji",
  "finland",
  "france",
  "gabon",
  "gambia",
  "georgia",
  "germany",
  "ghana",
  "greece",
  "grenada",
  "guatemala",
  "guinea",
  "guinea-bissau",
  "guyana",
  "haiti",
  "honduras",
  "hungary",
  "iceland",
  "india",
  "indonesia",
  "iran",
  "iraq",
  "ireland",
  "israel",
  "italy",
  "jamaica",
  "japan",
  "jordan",
  "kazakhstan",
  "kenya",
  "kiribati",
  "korea, north",
  "korea, south",
  "kosovo",
  "kuwait",
  "kyrgyzstan",
  "laos",
  "latvia",
  "lebanon",
  "lesotho",
  "liberia",
  "libya",
  "liechtenstein",
  "lithuania",
  "luxembourg",
  "madagascar",
  "malawi",
  "malaysia",
  "maldives",
  "mali",
  "malta",
  "marshall islands",
  "mauritania",
  "mauritius",
  "mexico",
  "micronesia",
  "moldova",
  "monaco",
  "mongolia",
  "montenegro",
  "morocco",
  "mozambique",
  "myanmar",
  "namibia",
  "nauru",
  "nepal",
  "netherlands",
  "new zealand",
  "nicaragua",
  "niger",
  "nigeria",
  "north macedonia",
  "norway",
  "oman",
  "pakistan",
  "palau",
  "panama",
  "papua new guinea",
  "paraguay",
  "peru",
  "philippines",
  "poland",
  "portugal",
  "qatar",
  "romania",
  "russia",
  "rwanda",
  "saint kitts and nevis",
  "saint lucia",
  "saint vincent and the grenadines",
  "samoa",
  "san marino",
  "sao tome and principe",
  "saudi arabia",
  "senegal",
  "serbia",
  "seychelles",
  "sierra leone",
  "singapore",
  "slovakia",
  "slovenia",
  "solomon islands",
  "somalia",
  "south africa",
  "south sudan",
  "spain",
  "sri lanka",
  "sudan",
  "suriname",
  "sweden",
  "switzerland",
  "syria",
  "taiwan",
  "tajikistan",
  "tanzania",
  "thailand",
  "togo",
  "tonga",
  "trinidad and tobago",
  "tunisia",
  "turkey",
  "turkmenistan",
  "tuvalu",
  "uganda",
  "ukraine",
  "united arab emirates",
  "united kingdom",
  "united states",
  "uruguay",
  "uzbekistan",
  "vanuatu",
  "vatican city",
  "venezuela",
  "vietnam",
  "yemen",
  "zambia",
  "zimbabwe",
];

const more = [
  " apple",
  "tree",
  "cat",
  "house",
  "car",
  "smiling sun",
  "flower",
  "star",
  "dog",
  "cupcake",
  "book",
  "bicycle",
  "cloud",
  "bird",
  "heart",
  "fish",
  "butterfly",
  "moon",
  "rainbow",
  "beach",
  "mountain",
  "dolphin",
  "snowflake",
  "castle",
  "guitar",
  "hot air balloon",
  "pizza",
  "sailboat",
  "lighthouse",
  "pineapple",
  "camera",
  "palm tree",
  "helicopter",
  "teapot",
  "snowman",
  "cactus",
  "sailboat",
  "watermelon",
  "seashell",
  "sunflower",
  "donut",
  "rocket",
  "bee",
  "spider",
  "ladybug",
  "mushroom",
  "dragonfly",
  "horse",
  "key",
  "lock",
  "door",
  "window",
  "clock",
  "lightbulb",
  "hammer",
  "nail",
  "saw",
  "ladder",
  "tent",
  "campfire",
  "marshmallow",
  "compass",
  "map",
  "globe",
  "paintbrush",
  "palette",
  "canvas",
  "rainbow",
  "thunderstorm",
  "waterfall",
  "desert",
  "volcano",
  "tornado",
  "jungle",
  "cave",
  "river",
  "lake",
  "beach",
  "forest",
  "waterfall",
  "canyon",
  "meadow",
  "iceberg",
  "castle",
  "city",
  "bridge",
  "roller coaster",
  "Ferris wheel",
  "carnival",
  "spaceship",
  "robot",
  "flying saucer",
  "knight",
  "dragon",
  "unicorn",
  "mermaid",
  "wizard",
  "superhero",
  "ballerina",
  "pirate",
  "clown",
  "ninja",
  "cowboy",
  "chef",
  "doctor",
  "firefighter",
  "police officer",
  "teacher",
  "spaceman",
  "diver",
  "scientist",
  "lifeguard",
  "pilot",
  "farmer",
  "rock star",
  "chef",
  "magician",
  "painter",
  "writer",
  "singer",
  "dancer",
  "swimmer",
  "surfer",
  "skater",
  "cyclist",
  "baker",
  "mechanic",
  "plumber",
  "gardener",
  "photographer",
  "director",
  "musician",
  "president",
  "king",
  "queen",
  "prince",
  "princess",
  "castle",
  "palace",
  "jungle",
  "zoo",
  "circus",
  "farm",
  "school",
  "hospital",
  "police station",
  "fire station",
  "post office",
  "library",
  "museum",
  "bakery",
  "supermarket",
  "restaurant",
  "cinema",
  "beach",
  "park",
  "playground",
  "space station",
  "submarine",
  "race car",
  "train",
  "plane",
  "boat",
  "spaceship",
  "hot air balloon",
  "bicycle",
  "motorcycle",
  "scooter",
  "skateboard",
  "tricycle",
  "helicopter",
  "car",
  "truck",
  "bus",
  "taxi",
  "camper van",
  "cruise ship",
  "yacht",
  "submarine",
  "rocket",
  "space shuttle",
  "satellite",
  "UFO",
  "rainbow",
  "lightning bolt",
  "cloud",
  "thunderstorm",
  "tornado",
  "hurricane",
  "snowstorm",
  "blizzard",
  "tsunami",
  "volcano",
  " earthquake",
  "forest",
  "desert",
  "jungle",
  "beach",
  "mountain",
  "cave",
  "river",
  "lake",
  " ocean",
  " island",
  "waterfall",
  "canyon",
  "valley",
  "glacier",
  "castle",
  "city",
  "bridge",
  "tower",
  "skyscraper",
  "house",
  " apartment building",
  "barn",
  "church",
  "lighthouse",
  "windmill",
  "pyramid",
  "sphinx",
  "temple",
  "statue",
  "fountain",
  "garden",
  "zoo",
  "circus",
  " amusement park",
  "stadium",
  "school",
  "hospital",
  "police station",
  "fire station",
  "post office",
  "library",
  "museum",
  "theater",
  "cinema",
  "concert hall",
  "mall",
  "market",
  "bakery",
  "supermarket",
  "restaurant",
  "cafe",
  "hotel",
  "motel",
  "castle",
  "space station",
  "submarine",
  "pirate ship",
  "race car",
  "sports car",
  "limousine",
  "school bus",
  "double-decker bus",
  "camper van",
  "fire truck",
  " ambulance",
  "police car",
  "tow truck",
  "garbage truck",
  "bulldozer",
  "crane",
  " excavator",
  "forklift",
  "tractor",
  "bicycle",
  "motorcycle",
  "scooter",
  "skateboard",
  "tricycle",
  "helicopter",
  "spaceship",
  "hot air balloon",
  "blimp",
  "biplane",
  "jet",
  "rocket",
  "space shuttle",
  "satellite",
  "UFO",
  "kite",
  "paper airplane",
  "frisbee",
  "boomerang",
  "yo-yo",
  "beach ball",
  "soccer ball",
  "basketball",
  "tennis ball",
  "baseball",
  "football",
  "golf ball",
  "bowling ball",
  "volleyball",
  "hockey puck",
  "pool ball",
  "pinball",
  "marbles",
  "chess board",
  "checkers board",
  "playing card",
  "puzzle",
  "Rubik's cube",
  "jigsaw puzzle",
  "Lego",
  "teddy bear",
  "doll",
  "puppet",
  "robot",
  "toy car",
  "train set",
  "bike",
  "scooter",
  "skateboard",
  "trampoline",
  "swing",
  "slide",
  "seesaw",
  "sandcastle",
  "kite",
  "hula hoop",
  "jump rope",
  "hopscotch",
  "merry-go-round",
  "Ferris wheel",
  "roller coaster",
  "bumper car",
  "video game",
  "computer",
  "laptop",
  "tablet",
  "smartphone",
  "smartwatch",
  "camera",
  "drone",
  "VR headset",
  "3D printer",
  "flashlight",
  "compass",
  "map",
  "globe",
  "magnifying glass",
  "telescope",
  "microscope",
  "binoculars",
  "hammer",
  "screwdriver",
  "wrench",
  "saw",
  "drill",
  "tape measure",
  "level",
  "ladder",
  "toolbox",
  "tool belt",
  "nail",
  "nut",
  "bolt",
  "hinge",
  "padlock",
  "chain",
  "rope",
  "ladder",
  "tent",
  "campfire",
  "marshmallow",
  "sleeping bag",
  "backpack",
  "compass",
  "map",
  "flashlight",
  "pocket knife",
  "canteen",
  "cooler",
  "first aid kit",
  "sunscreen",
  "bug spray",
  "fishing rod",
  "tackle box",
  "bait",
  "net",
  "water bottle",
  "sandcastle",
  "seashell",
  "starfish",
  "crab",
  "seagull",
  "sailboat",
  "beach towel",
  "beach umbrella",
  "beach chair",
  "beach ball",
  "surfboard",
  "snorkel",
  "mask",
  "fins",
  "scuba tank",
  "dolphin",
  "whale",
  "shark",
  "sea turtle",
  "coral reef",
  "beach",
  "sand dune",
  "palm tree",
  "hammock",
  "coconut",
  "cocktail",
  "beach party",
  "beach volleyball",
  "beach bonfire",
  "mountain",
  "cave",
  "waterfall",
  "hot spring",
  "canyon",
  "valley",
  "desert",
  " oasis",
  "sand dune",
  "camel",
  "scorpion",
  "snake",
  "vulture",
  "mirage",
  "cactus",
  "cowboy",
  "hat",
  "lasso",
  "saddle",
  "horseshoe",
  "bandana",
  "sheriff badge",
  "saloon",
  "cowboy boots",
  "rodeo",
  "Native American",
  "totem pole",
  "teepee",
  "buffalo",
  "dreamcatcher",
  "prairie",
  "wild west",
  "forest",
  "waterfall",
  "lake",
  "river",
  "campfire",
  "tent",
  "hiking trail",
  "backpack",
  "compass",
  "map",
  "flashlight",
  "binoculars",
  "wildlife",
  "deer",
  "bear",
  "fox",
  "rabbit",
  "squirrel",
  "raccoon",
  "skunk",
  "moose",
  "wolf",
  "mountain lion",
  "bison",
  "bobcat",
  "bird",
  " eagle",
  " owl",
  "hawk",
  "falcon",
  "vulture",
  "hummingbird",
  "woodpecker",
  "blue jay",
  "robin",
  "cardinal",
  "sparrow",
  "pigeon",
  "seagull",
  "duck",
  "goose",
  "swan",
  "flamingo",
  "peacock",
  "parrot",
  "toucan",
  "penguin",
  "puffin",
  "butterfly",
  "ladybug",
  "dragonfly",
  "grasshopper",
  "praying mantis",
  "beetle",
  "spider",
  "tarantula",
  "scorpion",
  "centipede",
  "millipede",
  "caterpillar",
  "chrysalis",
  "cocoon",
  "snake",
  "turtle",
  "tortoise",
  "crocodile",
  "frog",
  "toad",
  "salamander",
  "newt",
  "gecko",
  "chameleon",
  "dinosaur",
  "T-Rex",
  "triceratops",
  "stegosaurus",
  "velociraptor",
  "brachiosaurus",
  "pterodactyl",
  "woolly mammoth",
  "saber-toothed tiger",
  "dodo bird",
  "giant squid",
  "woolly rhinoceros",
  "giant sloth",
  "megalodon",
  "kraken",
  "basilisk",
  "phoenix",
  "minotaur",
  "griffin",
  "unicorn",
  "mermaid",
  "dragon",
  "Loch Ness monster",
  "Bigfoot",
  "Yeti",
  "chupacabra",
  "Mothman",
  "Jersey Devil",
  "Jackalope",
  "thunderstorm",
  "lightning bolt",
  "tornado",
  "hurricane",
  "snowstorm",
  "blizzard",
  "hailstorm",
  "monsoon",
  "rainbow",
  "cloud",
  "fog",
  "mist",
  "sun",
  "moon",
  "star",
  "comet",
  " asteroid",
  "meteor",
  "planet",
  "galaxy",
  "nebula",
  "black hole",
  "space station",
  "satellite",
  "UFO",
  " alien",
  "martian",
  "spaceship",
  "rocket",
  "space shuttle",
  "space probe",
  "moon rover",
  "space telescope",
  "space suit",
  "meteor shower",
  " eclipse",
  "spacewalk",
  "wormhole",
  "time machine",
  "spaceship battle",
  "laser",
  "phaser",
  "lightsaber",
  "teleporter",
  "transporter",
  "replicator",
  "holodeck",
  "warp drive",
  "cloaking device",
  "tractor beam",
  "force field",
  "plasma gun",
  "hoverboard",
  "robot",
  "cyborg",
  " android",
  "nanobot",
  "hologram",
  "virtual reality",
  "computer virus",
  "time travel",
  "parallel universe",
  "teleportation",
  "invisibility",
  "mind control",
  "cloning",
  "genetic engineering",
  "space colonization",
  "terraforming",
  "underwater exploration",
  "deep sea diving",
  "submarine",
  "shipwreck",
  "sunken treasure",
  "underwater cave",
  "coral reef",
  "jellyfish",
  "shark",
  "whale",
  "seahorse",
  "dolphin",
  "octopus",
  "crab",
  "lobster",
  "mermaid",
  "pirate",
  "treasure chest",
  "ship",
  "fishing boat",
  "submarine",
  "lighthouse",
  "beach",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
  "plank",
  "peg leg",
  "hook hand",
  "eye patch",
  "skull and crossbones",
  "tropical island",
  "desert island",
  "castaway",
  "palm tree",
  "hammock",
  "coconut",
  "beach hut",
  "bonfire",
  "surfboard",
  "seashell",
  "seagull",
  "dolphin",
  "crab",
  "turtle",
  "fish",
  "seahorse",
  "coral reef",
  "pirate",
  "treasure chest",
  "ship",
  "shipwreck",
  "compass",
  "map",
  "pirate flag",
  "telescope",
  "parrot",
  "sword",
  "cutlass",
  "treasure map",
  "buried treasure",
  "cannon",
];

const total = [
  ...memes,
  ...easy,
  ...phrases,
  ...games,
  ...anime,
  ...movies,
  ...shows,
  ...books,
  ...foods,
  ...countries,
  ...more,
];

const set = new Set();
const duplicates = [];

for (const entry of total) {
  let cleaned = entry.trim().toLowerCase();

  if (set.has(cleaned)) {
    duplicates.push(cleaned);
  } else {
    set.add(cleaned);
  }
}

const arr = [...set];
fs.writeFileSync("./words.json", JSON.stringify(arr, undefined, 2));
fs.writeFileSync("./duplicates.json", JSON.stringify(duplicates, undefined, 2));
